apiVersion: v1
data:
  config.yaml: |-
    namespace: "{{- .Release.Namespace -}}"
    deployment: "ng-plus-apigw"
    host: "{{ include "serverName" . -}}"
    domain: "{{- include "apigwDomain" . -}}"
    path: "/_synced"
    sync_timeout: 100
    request_deadline: 1000
kind: ConfigMap
metadata:
  name: ng-plus-syncer
