openapi: 3.0.3
info:
    title: Syncer
    description: Service achieving atomic synchronization for jwt token in ng-plus distributed environment
    version: "1.0"
servers:
    - url: http://localhost:8080
paths:
    /v1/synced:
        get:
            tags:
                - checker
            summary: get checker
            description: Get last full report
            operationId: checker#get
            parameters:
                - name: X-Nginx-Origin
                  in: header
                  description: nginx instance origin of the request
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: nginx instance origin of the request
                    example: Perspiciatis provident consequatur repellat enim.
                  example: Vitae qui id qui.
                - name: X-Auth-Token
                  in: header
                  description: token cookie for synchronization check
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: token cookie for synchronization check
                    example: Necessitatibus inventore.
                  example: Quod rerum facere voluptas quisquam reiciendis.
            responses:
                "200":
                    description: OK response.
                    headers:
                        X-Token-Status:
                            schema:
                                type: string
                                default: synced
                                example: Atque pariatur qui illum dolores quo omnis.
                            example: Qui cum ab possimus.
components: {}
tags:
    - name: checker
      description: Check the replicas of nginx instancies
