swagger: "2.0"
info:
    title: Syncer
    description: Service achieving atomic synchronization for jwt token in ng-plus distributed environment
    version: ""
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /v1/synced:
        get:
            tags:
                - checker
            summary: get checker
            description: Get last full report
            operationId: checker#get
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/CheckerGetResponseBody'
            schemes:
                - http
definitions:
    CheckerGetResponseBody:
        title: 'Mediatype identifier: app/vnd.sync; view=default'
        type: object
        properties:
            status:
                type: string
                default: synced
                example: Aut ut nam eos.
        description: GetResponseBody result type (default view)
        example:
            status: Corrupti hic architecto reprehenderit velit reiciendis.
