swagger: "2.0"
info:
    title: Syncer
    description: Service achieving atomic synchronization for jwt token in ng-plus distributed environment
    version: ""
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /v1/synced:
        get:
            tags:
                - checker
            summary: get checker
            description: Get last full report
            operationId: checker#get
            parameters:
                - name: X-Nginx-Origin
                  in: header
                  description: nginx instance origin of the request
                  required: true
                  type: string
                - name: X-Feg-Token
                  in: header
                  description: token cookie for synchronization check
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    headers:
                        X-Token-Status:
                            type: string
                            default: synced
            schemes:
                - http
