# Default values for Helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  //repository: docker-registry.default.svc:5000/shared-images/ftn-nginx-plus-rhel7
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  syncerTag: build-77cf146

feg:
  t:
    cz: api.ocp01-shared.t.dc1.cz.ipa.ifortuna.cz
    ro: api.ocp01-shared.t.dc1.cz.ipa.ifortuna.cz
    cp: api.ocp01-shared.t.dc1.cz.ipa.ifortuna.cz
    pl: api.ocp01-shared.t.dc1.cz.ipa.ifortuna.cz
    hr: api.ocp01-shared.t.dc1.cz.ipa.ifortuna.cz
    sk: api.ocp01-shared.t.dc1.cz.ipa.ifortuna.cz
    shared: api.ocp01-shared.t.dc1.cz.ipa.ifortuna.cz
  s:
    cz: api.ocp02-shared.s.dc1.cz.ipa.ifortuna.cz
    ro: api.ocp02-shared.s.dc1.cz.ipa.ifortuna.cz
    cp: api.ocp02-shared.s.dc1.cz.ipa.ifortuna.cz
    pl: api.ocp02-shared.s.dc1.cz.ipa.ifortuna.cz
    sk: api.ocp02-shared.s.dc1.cz.ipa.ifortuna.cz
    hr: api.ocp02-shared.s.dc1.cz.ipa.ifortuna.cz
  p:
    cp: api.ocp01-cp.p.dc1.cz.ipa.ifortuna.cz
    cz: api.ocp01-cz.p.dc1.cz.ipa.ifortuna.cz
    ro: api.ocp01-ro.p.dc1.cz.ipa.ifortuna.cz
    pl: api.ocp01-pl.p.dc1.pl.ipa.ifortuna.cz
    sk: api.ocp01-sk.p.dc1.sk.ipa.ifortuna.cz
    hr: api.ocp01-hr.p.dc1.hr.ipa.ifortuna.cz
  d:
    cz: api.ocp01-shared.d.dc1.cz.ipa.ifortuna.cz
